### ISSUE TITLE
Rich snippets for embedded internal content

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3406] opened 2020-06-27 12:34 UTC
- [ ] Consistent replacement of embedded links to internal content (e.g. CMS articles) with the corresponding BBCode
- [ ] The BBCode should display more information if available (like teaser text, title picture, etc.)

**Comment by TimWolla** [comment] 2021-02-09 11:11
Duplicate of #3956

**Closed** 2021-02-19 12:23 UTC
Labels: Discussion
