### ISSUE TITLE
JavaScript error when selecting the page type to create

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5386] opened 2023-04-03 20:08 UTC
```
Add.js?t=1680548929:42 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at WoltlabCoreDialogElement.<anonymous> (Add.js?t=1680548929:42:52)
    at #dispatchPrimaryEvent (woltlab-core-dialog.js?t=1680548929:168:18)
    at HTMLDialogElement.<anonymous> (woltlab-core-dialog.js?t=1680548929:149:43)
(anonym) @ Add.js?t=1680548929:42
#dispatchPrimaryEvent @ woltlab-core-dialog.js?t=1680548929:168
(anonym) @ woltlab-core-dialog.js?t=1680548929:149
```

```JS
            dialog.addEventListener("primary", () => {
                const pageTypeSelection = content.querySelector('input[name="pageType"]:checked');
                const pageType = pageTypeSelection.value;
                let isMultilingual = "0";
                if (this.#supportsI18n) {
                    const i18nSelection = content.querySelector('input[name="isMultilingual"]:checked');
                    isMultilingual = i18nSelection.value; // <= this line
                }
                window.location.href = this.#link.replace("{$pageType}", pageType).replace("{$isMultilingual}", isMultilingual);
            });
```

**Comment by TimWolla** [comment] 2023-04-04 07:10
Duplicate of #5383

**Comment by TimWolla** [comment] 2023-04-04 07:11
Please retry with the latest version and reopen, if this is a different, but similar issue.

**Closed by TimWolla** 2023-04-04 07:11 UTC
