### ISSUE TITLE
2FA: Log 2FA-failures like password-failures during logins

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4361] opened 2021-07-03 14:14 UTC
Since failed logins are logged as invalid username and invalid password, it might be cool to differentiate 2fa-failures as a own type of login-failure.
This makes logins more visible that succeeded for the password but failed for the second factor.

**Comment by TimWolla** [comment] 2021-07-05 07:42
Duplicate of #3395

**Comment by TimWolla** [comment] 2021-07-05 07:45
One of the reasons this is not implemented yet is that it's not entirely clear what exactly would qualify as a failed MFA attempt.

Specifically consider the following:

1. An attacker logs into an account with a stolen password.
2. The attacker notices that the account enabled multi-factor authentication.
3. Because the attacker knows that they don't have the necessary secrets they don't even attempt to send anything and simply close the page to retry with another account.

Would this be a failed MFA attempt or not?

**Comment by TimWolla** [comment] 2021-07-05 07:46
I'm closing this at this point, because it is a duplicate. But I cross-referenced it within the other issue. Nonetheless feel free to comment on the closed issue.

**Closed by TimWolla** 2021-07-05 07:46 UTC
