### ISSUE TITLE
Two-click solution for external media

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3226] opened 2020-05-03 15:52 UTC
It should be possible to configure that external media (videos and images) are not directly included in texts but that users have to confirm loading the media via an additional click.

Two possibilities discussed in the original thread:
- Simple solution: each media element requires explicit consent
- Persistent solution: loading media element from the same domain is consented to permanently without any further prompts (How would users revoke their consent?)

see https://community.woltlab.com/thread/268329-extra-klick-l%C3%B6sung-f%C3%BCr-dsgvo-kompatible-externe-bilder-und-medien/

**Comment by TimWolla** [comment] 2020-05-20 11:04
Possible duplicate of #3192

**Closed** 2020-06-12 18:18 UTC
Labels: New Feature
