### ISSUE TITLE
5.4: Error converting WebP with ImageMagick

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4074] opened 2021-03-12 19:08 UTC
We need a check whether the package `webp` is installed on the server when using ImageMagick:

```
Fri, 12 Mar 2021 18:54:56 +0000
Message: delegate failed `'cwebp' -quiet %Q '%i' -o '%o'' @ error/delegate.c/InvokeDelegate/1949
PHP version: 8.0.3
WoltLab Suite version: 5.4.0 Alpha 1
Request URI: POST /index.php?ajax-upload/&t=
Referrer: /avatar-edit/
User Agent: n/a
Peak Memory Usage: 4657616/0
======
Error Class: ImagickException
Error Message: delegate failed `'cwebp' -quiet %Q '%i' -o '%o'' @ error/delegate.c/InvokeDelegate/1949
Error Code: 415
File: /lib/system/image/adapter/ImagickImageAdapter.class.php (519)
Extra Information: -
Stack Trace: [{"file":"\/lib\/system\/image\/adapter\/ImagickImageAdapter.class.php","line":519,"function":"writeimages","class":"Imagick","type":"->","args":[]},{"file":"\/lib\/system\/image\/adapter\/ImageAdapter.class.php","line":419,"function":"saveImageAs","class":"wcf\\system\\image\\adapter\\ImagickImageAdapter","type":"->","args":[]},{"file":"\/lib\/data\/user\/avatar\/UserAvatarEditor.class.php","line":148,"function":"saveImageAs","class":"wcf\\system\\image\\adapter\\ImageAdapter","type":"->","args":[]},{"file":"\/lib\/system\/upload\/AvatarUploadFileSaveStrategy.class.php","line":120,"function":"createAvatarVariant","class":"wcf\\data\\user\\avatar\\UserAvatarEditor","type":"->","args":[]},{"file":"\/lib\/system\/upload\/UploadHandler.class.php","line":132,"function":"save","class":"wcf\\system\\upload\\AvatarUploadFileSaveStrategy","type":"->","args":[]},{"file":"\/lib\/data\/user\/avatar\/UserAvatarAction.class.php","line":87,"function":"saveFiles","class":"wcf\\system\\upload\\UploadHandler","type":"->","args":[]},{"file":"\/lib\/data\/AbstractDatabaseObjectAction.class.php","line":216,"function":"upload","class":"wcf\\data\\user\\avatar\\UserAvatarAction","type":"->","args":[]},{"file":"\/lib\/action\/AJAXProxyAction.class.php","line":86,"function":"executeAction","class":"wcf\\data\\AbstractDatabaseObjectAction","type":"->","args":[]},{"file":"\/lib\/action\/AJAXInvokeAction.class.php","line":102,"function":"invoke","class":"wcf\\action\\AJAXProxyAction","type":"->","args":[]},{"file":"\/lib\/action\/AbstractAction.class.php","line":53,"function":"execute","class":"wcf\\action\\AJAXInvokeAction","type":"->","args":[]},{"file":"\/lib\/action\/AJAXInvokeAction.class.php","line":65,"function":"__run","class":"wcf\\action\\AbstractAction","type":"->","args":[]},{"file":"\/lib\/system\/request\/Request.class.php","line":89,"function":"__run","class":"wcf\\action\\AJAXInvokeAction","type":"->","args":[]},{"file":"\/lib\/system\/request\/RequestHandler.class.php","line":119,"function":"execute","class":"wcf\\system\\request\\Request","type":"->","args":[]},{"file":"\/index.php","line":11,"function":"handle","class":"wcf\\system\\request\\RequestHandler","type":"->","args":[]}]
```

**Comment by SoftCreatR** [comment] 2021-04-03 20:39
That's what we use in TinyImg to determine delegate support:

```php
if (!in_array('WEBP', \Imagick::queryFormats())) {
    throw new \Exception('Unsupported format');
}
```

**Comment by TimWolla** [comment] 2021-04-26 09:17
Do you happen to have a reproducer for this (e.g. a Dockerfile)?

**Comment by SoftCreatR** [comment] 2021-04-27 10:11
Simply install/compile IM without `libwebp`.

```dockerfile
FROM debian:buster-slim

ARG IM_VERSION=7.0.11-6

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y git make gcc pkg-config autoconf curl g++ libpng16-16 libpng-dev libjpeg62-turbo libjpeg62-turbo-dev && \
    git clone https://github.com/ImageMagick/ImageMagick.git && \
    cd ImageMagick && git checkout ${IM_VERSION} && \
    ./configure --without-magick-plus-plus --disable-docs --disable-static && \
    make && make install && \
    ldconfig /usr/local/lib && \
    apt-get remove --autoremove --purge -y gcc make curl g++ yasm git autoconf pkg-config libpng-dev libjpeg62-turbo-dev && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /ImageMagick

ENTRYPOINT ["convert"]
```

**Comment by TimWolla** [comment] 2021-04-27 10:14
> Simply install/compile IM without `libwebp`.

Do you also happen to have a version with Imagick (PHP) support?

**Comment by SoftCreatR** [comment] 2021-04-27 10:17
Never needed that. But something like that should do the trick already:

```dockerfile
FROM php:7.2

RUN apt-get update && \
    apt-get install -y libmagickwand-dev && \
    pecl install imagick && \
    docker-php-ext-enable imagick && \
    apt-get remove --purge -y automake autotools-dev bzip2-doc fontconfig gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-rsvg-2.0 icu-devtools javascript-common libblkid-dev libbz2-dev libcairo-gobject2 libcairo-script-interpreter2 libcairo2 libcairo2-dev libcroco3 libdatrie1 libdjvulibre-dev libdjvulibre-text libdjvulibre21 libelf1 libexif-dev libexif-doc libexif12 libexpat1-dev libffi-dev libfontconfig1-dev libfreetype6-dev libfribidi0 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev libgirepository-1.0-1 libglib2.0-bin libglib2.0-data libglib2.0-dev libglib2.0-dev-bin libgraphite2-3 libharfbuzz0b libice-dev libice6 libicu-dev libilmbase-dev libilmbase23 libjbig-dev libjpeg-dev libjpeg62-turbo-dev libjs-jquery libjxr-tools libjxr0 liblcms2-dev liblqr-1-0-dev libltdl-dev liblzma-dev liblzo2-2 libmagickcore-6-arch-config libmagickcore-6-headers libmagickcore-6.q16-6-extra libmagickcore-6.q16-dev libmagickwand-6-headers libmagickwand-6.q16-dev libmagickwand-dev libmount-dev libmpdec2 libopenexr-dev libopenexr23 libopenjp2-7-dev libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpixman-1-0 libpixman-1-dev libpng-dev libpng-tools libpthread-stubs0-dev libpython3-stdlib libpython3.7-minimal libpython3.7-stdlib libreadline7 librsvg2-2 librsvg2-common librsvg2-dev libselinux1-dev libsepol1-dev libsm-dev libsm6 libthai-data libthai0 libtiff-dev libtiffxx5 libtool libwmf-dev libwmf0.2-7 libx11-dev libxau-dev libxcb-render0 libxcb-render0-dev libxcb-shm0 libxcb-shm0-dev libxcb1-dev libxdmcp-dev libxext-dev libxml2-dev libxrender-dev libxrender1 libxt-dev libxt6 mime-support python3 python3-distutils python3-lib2to3 python3-minimal python3.7 python3.7-minimal readline-common shared-mime-info uuid-dev x11-common x11proto-core-dev x11proto-dev x11proto-xext-dev xorg-sgml-doctools xtrans-dev zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by TimWolla** [comment] 2021-04-27 10:19
> But something like that should do the trick already:

Doesn't, unfortunately. I was unable to reproduce this with my local docker image (PHP 7.4, due to the PHP 8 + Imagick situation):

```
FROM php:7.4-fpm

RUN	export DEBIAN_FRONTEND="noninteractive"; \
	savedAptMark="$(apt-mark showmanual)"; \
	buildDeps=" \
		libpng-dev \
		libfreetype6-dev \
		libgmp-dev \
		libicu-dev \
		libjpeg62-turbo-dev \
		libjpeg-dev \
		libpq-dev \
		libmagickwand-dev \
	"; \
	set -ex; \
	apt-get update; \
	apt-get install -y $buildDeps --no-install-recommends; \
	docker-php-ext-install -j "$(nproc)" opcache; \
	docker-php-ext-install -j "$(nproc)" pdo_mysql mysqli; \
	docker-php-ext-install -j "$(nproc)" pdo_pgsql; \
	docker-php-ext-configure gd --with-jpeg; \
	docker-php-ext-install -j "$(nproc)" gd; \
	docker-php-ext-install exif; \
	docker-php-ext-install intl; \
	docker-php-ext-install gmp; \
	pecl install -o -f imagick; \
	docker-php-ext-enable imagick; \
	pecl install -o -f redis; \
	docker-php-ext-enable redis; \
	pecl install -o -f xdebug; \
	docker-php-ext-enable xdebug; \
	apt-mark auto '.*' > /dev/null; \
	apt-mark manual $savedAptMark; \
	ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
		| awk '/=>/ { print $3 }' \
		| sort -u \
		| xargs -r dpkg-query -S \
		| cut -d: -f1 \
		| sort -u \
		| xargs -rt apt-mark manual; \
	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
	rm -rf /var/lib/apt/lists/*; \
	rm -rf /tmp/pear;
```

**Comment by SoftCreatR** [comment] 2021-04-27 10:27
It could be, that webp support is shipped with libmagicwand.

**Comment by TimWolla** [comment] 2021-04-27 10:29
Sure. But that doesn't explain how to trigger @mutec's error message. If it just happens on say, ancient libmagick versions, then I'm inclined to just ignore this.

In fact I'm a bit confused why Imagick appears to shell out in the initial issue. webp support with my Dockerfile was provided using a shared object that was dynamically loaded. Not by spawning an executable.

**Comment by SoftCreatR** [comment] 2021-04-27 10:50
Well, this can also happen with ImageMagick 7. I'm not 100% sure, in which cases the webp/libwebp package could be missing, but I've seen several cases, where webp support wasn't available because of missing dependencies, even on newer operating systems.

I'll try to build a Docker container later this day.

**Comment by TimWolla** [comment] 2021-04-30 07:31
> I'll try to build a Docker container later this day.

Did you get around to testing this, yet?

**Comment by SoftCreatR** [comment] 2021-04-30 07:40
Nah, didn't had the time as expected. I'll do this later this day.

**Comment by TimWolla** [comment] 2021-05-10 13:37
@SoftCreatR Friendly reminder.

**Comment by TimWolla** [comment] 2021-05-12 07:08
Thank you for the feedback. I'm closing this issue at this point. Feel free to reopen / open a new issue if you happen to come across it with a clear reproducer.

**Closed by TimWolla** 2021-05-12 07:08 UTC
Labels: Bug
