### ISSUE TITLE
Validation of SingleSelectionFormField as non-required and nullable

### ISSUE THREAD

**Issue by Fighter456** [WoltLab/WCF#5342] opened 2023-03-07 20:12 UTC
Is it intended that submitting a `SingleSelectionFormField` in combination with `required(false)` and `nullable(true)` will not allow saving because validation will fail?

For my part, I would have expected `null` to be provided for the database field since the user didn't specify it (selected value). And in that case, of course, it is not expected.

https://github.com/WoltLab/WCF/blob/bb349f5cfb64ec93ad08f1485a938f851e891cee/wcfsetup/install/files/lib/system/form/builder/field/SingleSelectionFormField.class.php#L88-L98

**Comment by TimWolla** [comment] 2023-03-08 08:27
Duplicate of #5265

**Closed by TimWolla** 2023-03-08 08:27 UTC
