### ISSUE TITLE
Style description language dropdown not working

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5166] opened 2022-12-07 09:16 UTC
The language switch within the style add / edit form (description) does nothing, when clicking on it.

![image](https://user-images.githubusercontent.com/81188/206138364-a032febe-15ab-4ffc-9e96-7eee07cb3f69.png)

**Comment by TimWolla** [comment] 2022-12-07 09:19
Duplicate of #5134

**Closed by TimWolla** 2022-12-07 09:19 UTC
