### ISSUE TITLE
Database-PIP: Error column doesn't exist and can't be renamed while renaming

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4363] opened 2021-07-03 19:03 UTC
1. Before running the PIP the column is called `public`.
2. Running the PIP results in
`Das Datenbanklayout konnte aufgrund folgender Fehler nicht aktualisiert werden: Die Spalte table.public existiert nicht und kann deshalb nicht umbenannt werden.`
3. Inspecting the table shows that the column has been renamed by the PIP; the next change/rename has not been performed in favor of the abort.

Used code:
```PHP
return [
	PartialDatabaseTable::create('table')
		->columns([
			DefaultFalseBooleanDatabaseTableColumn::create('public')
				->renameTo('isPublic'),
		]),
];
```

may be related to #4362

**Comment by Gravatronics** [comment] 2021-07-05 09:35
Duplicate of #4362.

**Closed by Gravatronics** 2021-07-05 09:35 UTC
Labels: Needs Triage
