### ISSUE TITLE
style variables not added during upgrade

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5361] opened 2023-03-15 20:02 UTC
- [ ] `wcfSidebarBorder`
- [ ] `wcfHeaderMenuDropdownBorder `
- [ ] `individualScssDarkMode`

**Comment by mutec** [comment] 2023-03-15 20:33
same for all darkmode default values

**Comment by TimWolla** [comment] 2023-03-16 08:14
Effectively a duplicate of #5354. I've justed added the two `wcf*` variables to the list there.

**Closed by TimWolla** 2023-03-16 08:14 UTC
