### ISSUE TITLE
Use font stack instead of 3rd party fonts by default

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#4017] opened 2021-02-23 19:04 UTC
A while ago, we switched from default Open Sans to a default font stack:

```css
font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;
```

From my experience, most people can't tell a huge difference in the UI* but avoiding the use of Open Sans or any other 3rd party font greatly improves the performance since they don't require loading any additional font files thus there's no FOIT and no need for additional preload requests, etc.

\* = Of course there are visual differences and of course there are enough people who will notice these differences, but the performance advantage outweighs the disadvantages caused by the visual differences, which are pretty minimal IMHO: 

https://codepen.io/SoftCreatR/full/BaQmYmr

So my idea is to use the proposed font stack, instead of Open Sans by default for the default- and for any new style.

**Comment by dtdesign** [comment] 2021-02-23 20:13
Duplicate of #3970

**Closed by dtdesign** 2021-02-23 20:13 UTC

**Comment by SoftCreatR** [comment] 2021-02-23 20:20
@dtdesign U sure, that this is a duplicate? I mean, I can't find any information in your issue, that using a system UI font stack is planned to be the default (instead of Open Sans) in the future, but If that's the case: 👍

**Comment by dtdesign** [comment] 2021-02-23 20:27
Yes, it absolutely is. I've looked into this for quite some time before creating the issue, in particular making sure that we do use a matching font stack for code-style elements.

**Comment by SoftCreatR** [comment] 2021-02-23 20:32
Yeah, we use one too:

```css
font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, 'Courier New', monospace;
```
