### ISSUE TITLE
Overhaul the search drop-down

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3393] opened 2020-06-25 16:51 UTC
The search drop-down is a legacy component that lacks behind in terms of UX:
- The behavior for selecting keywords from the list is quirky.
- Live results could greatly improve the UX by allowing the user to quickly refine their search term based on results.

**Comment by TimWolla** [comment] 2020-06-25 16:52
Related: #3263

**Comment by Gravatronics** [comment] 2021-04-14 11:37
Duplicate of #3959.

**Closed by Gravatronics** 2021-04-14 11:37 UTC
Labels: Discussion
