### ISSUE TITLE
PHP 8: Problem with AbstractDatabaseObjectAction

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#3553] opened 2020-09-08 00:39 UTC
When trying to update packages, an exception will be thrown:

```
<<<<<<<<38d3aa4e4d368c7dba9c3017e7ae3d991691e0f9<<<<
Tue, 08 Sep 2020 00:37:09 +0000
Message: Unknown named parameter $packages
PHP version: 8.0.0beta3
WoltLab Suite version: 5.2.8
Request URI: /acp/index.php?ajax-proxy/&t=da51122a43dbfdf55f643be08136af23419e21ab
Referrer: 
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Peak Memory Usage: 2001904/134217728
======
Error Class: Error
Error Message: Unknown named parameter $packages
Error Code: 0
File: /lib/data/AbstractDatabaseObjectAction.class.php (190)
Extra Information: -
Stack Trace: [{"file":"\/lib\/data\/AbstractDatabaseObjectAction.class.php","line":190,"function":"call_user_func_array","class":"","type":"","args":[]},{"file":"\/lib\/action\/AJAXProxyAction.class.php","line":72,"function":"validateAction","class":"wcf\\data\\AbstractDatabaseObjectAction","type":"->","args":[]},{"file":"\/lib\/action\/AJAXInvokeAction.class.php","line":94,"function":"invoke","class":"wcf\\action\\AJAXProxyAction","type":"->","args":[]},{"file":"\/lib\/action\/AbstractAction.class.php","line":47,"function":"execute","class":"wcf\\action\\AJAXInvokeAction","type":"->","args":[]},{"file":"\/lib\/action\/AJAXInvokeAction.class.php","line":61,"function":"__run","class":"wcf\\action\\AbstractAction","type":"->","args":[]},{"file":"\/lib\/system\/request\/Request.class.php","line":83,"function":"__run","class":"wcf\\action\\AJAXInvokeAction","type":"->","args":[]},{"file":"\/lib\/system\/request\/RequestHandler.class.php","line":107,"function":"execute","class":"wcf\\system\\request\\Request","type":"->","args":[]},{"file":"\/acp\/index.php","line":9,"function":"handle","class":"wcf\\system\\request\\RequestHandler","type":"->","args":[]}]
<<<<
```

**Comment by SoftCreatR** [comment] 2020-09-08 00:47
This seems to be a general problem with the AbstractDatabaseObjectAction as it fails all the time, e.g. when creating a forum post:

```
<<<<<<<<db416b86867675afa62cfc416d3a149e4abddac2<<<<
Tue, 08 Sep 2020 00:45:52 +0000
Message: Unknown named parameter $objectID
PHP version: 8.0.0beta3
WoltLab Suite version: 5.2.8
Request URI: /forum/index.php?ajax-proxy/&t=572f1d410e297635e14a8d2c2b6b409544de4007
Referrer: 
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Peak Memory Usage: 3658808/268435456
======
Error Class: Error
Error Message: Unknown named parameter $objectID
Error Code: 0
File: /lib/data/AbstractDatabaseObjectAction.class.php (190)
Extra Information: -
Stack Trace: [{"file":"\/lib\/data\/AbstractDatabaseObjectAction.class.php","line":190,"function":"call_user_func_array","class":"","type":"","args":[]},{"file":"\/lib\/action\/AJAXProxyAction.class.php","line":72,"function":"validateAction","class":"wcf\\data\\AbstractDatabaseObjectAction","type":"->","args":[]},{"file":"\/lib\/action\/AJAXInvokeAction.class.php","line":94,"function":"invoke","class":"wcf\\action\\AJAXProxyAction","type":"->","args":[]},{"file":"\/lib\/action\/AbstractAction.class.php","line":47,"function":"execute","class":"wcf\\action\\AJAXInvokeAction","type":"->","args":[]},{"file":"\/lib\/action\/AJAXInvokeAction.class.php","line":61,"function":"__run","class":"wcf\\action\\AbstractAction","type":"->","args":[]},{"file":"\/lib\/system\/request\/Request.class.php","line":83,"function":"__run","class":"wcf\\action\\AJAXInvokeAction","type":"->","args":[]},{"file":"\/lib\/system\/request\/RequestHandler.class.php","line":107,"function":"execute","class":"wcf\\system\\request\\Request","type":"->","args":[]},{"file":"\/forum\/index.php","line":9,"function":"handle","class":"wcf\\system\\request\\RequestHandler","type":"->","args":[]}]
<<<<
```

**Comment by TimWolla** [comment] 2020-09-08 07:30
Duplicate of #3490

**Comment by TimWolla** [comment] 2020-09-08 07:31
Update to WoltLab Suite 5.2.9, please. It contains the fix.

**Closed by TimWolla** 2020-09-08 07:31 UTC
